### ISSUE TITLE
Add extra details in Atlassian Outage

### ISSUE THREAD

**Issue by electron0zero** [electron0zero/failure-modes#77]
https://newsletter.pragmaticengineer.com/p/scoop-atlassian?ref=blog.pragmaticengineer.com

**Comment by electron0zero** [comment]
also add https://newsletter.pragmaticengineer.com/p/inside-the-datadog-outage

**Comment by amanv8060** [comment]
https://www.atlassian.com/engineering/post-incident-review-april-2022-outage
